# Aplicação
spring.application.name=bilhetica

# Base de dados
spring.datasource.url=jdbc:postgresql://localhost:5434/bilhetica
spring.datasource.username=bilhetica
spring.datasource.password=bilhetica123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Servidor
server.port=8080

# Logs
logging.level.pt.uminho.mei.bilhetica=DEBUG
